development:
  adapter: postgresql
  encoding: unicode
  database: phonic_panel_development
  pool: 5
  username: Alan
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: phonic_panel_test
  pool: 5
  username:
  password:

